Repository anshumansinha18/webster, pull requests merged in 2021-09, with the labels that each got.

#8 Create readme.md
  readme.md
Labels: good first issue, hacktoberfest2021, hacktoberfest

#12 Added the footer.
  index.html
  styles.css
Labels: hacktoberfest-accepted

#10 Update readme.md
  readme.md
Labels: hacktoberfest2021, hacktoberfest, hacktoberfest-accepted
